const $=x=>document.getElementById(x);
let tf='15min',pair='EUR/USD',chart,series,bot=false,cache={},liveTimer,historicalTimer;
let account={balance:10000,position:null,trades:0};
$('end').value=new Date().toISOString().slice(0,10);
function E(a,n){let k=2/(n+1),v=a[0];return a.map(x=>v=x*k+v*(1-k))}
function R(a){if(a.length<15)return 50;let g=0,l=0,n=Math.min(14,a.length-1);for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];d>0?g+=d:l-=d}return l?100-100/(1+(g/n)/(l/n)):100}
async function api(interval,start,end){let q=new URLSearchParams({interval,symbol:pair});if(start)q.set('start',start);if(end)q.set('end',end);let r=await fetch('/.netlify/functions/market?'+q);let text=await r.text();if(!r.ok)throw Error(text);return JSON.parse(text)}
async function quote(){let r=await fetch('/.netlify/functions/quote?symbol='+encodeURIComponent(pair));let text=await r.text();if(!r.ok)throw Error(text);return JSON.parse(text)}
function init(){chart=LightweightCharts.createChart($('chart'),{layout:{background:{color:'#091624'},textColor:'#aab8c6'},grid:{vertLines:{color:'#10253a'},horzLines:{color:'#10253a'}},timeScale:{timeVisible:true}});series=chart.addSeries(LightweightCharts.CandlestickSeries,{});addEventListener('resize',()=>chart.applyOptions({width:$('chart').clientWidth}));chart.applyOptions({width:$('chart').clientWidth})}
function periodSeconds(i){return i==='15min'?900:i==='1h'?3600:14400}
function candleTime(ts,i=tf){let p=periodSeconds(i);return Math.floor(ts/p)*p}
function applyQuote(q){if(!q?.ok||!Number.isFinite(+q.price))return;let d=cache[tf]||[],price=+q.price,t=candleTime(+q.timestamp||Date.now()/1000);if(!d.length)return;let last=d[d.length-1];if(t<last.time)return;if(t>last.time){last={time:t,open:price,high:price,low:price,close:price};d=[...d,last];if(d.length>5000)d.shift()}else{last={...last,high:Math.max(last.high,price),low:Math.min(last.low,price),close:price};d=[...d.slice(0,-1),last]}cache[tf]=d;series.update(last);$('price').textContent=price.toFixed(pair.includes('JPY')?3:5);updatePosition(price);$('source').textContent='Twelve Data · live';$('connection').textContent='● LIVE';$('connection').style.color='#35d995';if(bot)analyze()}
async function load(){try{$('connection').textContent='● LOADING';let d=await api(tf);cache[tf]=d.values;series.setData(d.values);let p=d.values.at(-1).close;$('price').textContent=p.toFixed(pair.includes('JPY')?3:5);$('source').textContent=d.source||'Twelve Data';$('connection').textContent='● LIVE';$('connection').style.color='#35d995';if(bot)analyze()}catch(e){$('connection').textContent='● DATA ERROR';$('connection').style.color='#ee6872';$('reason').textContent='Market data error: '+e.message;console.error(e)}}
async function live(){try{applyQuote(await quote())}catch(e){$('connection').textContent='● QUOTE ERROR';$('connection').style.color='#d7a84b';console.error(e)}}
function decision(d,mode){let a=d.map(x=>x.close),p=a.at(-1),prev=a.at(-2),e20=E(a,20).at(-1),e50=E(a,50).at(-1),e200=E(a,200).at(-1),r=R(a),side=e50>e200&&p>e200?'BUY':e50<e200&&p<e200?'SELL':null;if(mode==='trend')return{side,e50,e200};let distance=Math.abs(p-e20)/p;let pull=distance<.003;if(mode==='setup')return{side,ready:!!side&&pull&&((side==='BUY'&&r>=35&&r<=70)||(side==='SELL'&&r>=30&&r<=65))};return{side,ready:!!side&&((side==='BUY'&&p>=prev)||(side==='SELL'&&p<=prev))}}
function levels(side,d){let p=d.at(-1).close,sl=side==='BUY'?Math.min(...d.slice(-8).map(x=>x.low)):Math.max(...d.slice(-8).map(x=>x.high)),risk=Math.max(Math.abs(p-sl),pair.includes('JPY')?.05:.0005),tp=side==='BUY'?p+risk*2:p-risk*2;return{p,sl,tp,risk}}
function renderLevels(x){let f=v=>v.toFixed(pair.includes('JPY')?3:5);$('entry').textContent=f(x.p);$('sl').textContent=f(x.sl);$('tp').textContent=f(x.tp)}
function analyze(){try{let m15=cache['15min'],h1=cache['1h'],h4=cache['4h'];if(!m15||!h1||!h4)return;let T=decision(h4,'trend'),S=decision(h1,'setup'),M=decision(m15,'entry');let side=T.side&&T.side===S.side&&S.ready&&M.side===T.side&&M.ready?T.side:'WAIT';$('decision').textContent=side;$('decision').className=side.toLowerCase();$('reason').textContent=side==='WAIT'?'No high-quality alignment yet. The bot waits rather than force a trade.':`4H trend, 1H pullback and 15m confirmation align: ${side}. Paper trade only.`;$('checks').innerHTML=`<div class="check">4H Trend <b class="${T.side?'ok':'wait'}">${T.side||'WAIT'}</b></div><div class="check">1H Pullback <b class="${S.ready?'ok':'wait'}">${S.ready?S.side:'WAIT'}</b></div><div class="check">15m Confirmation <b class="${M.ready?'ok':'wait'}">${M.ready?M.side:'WAIT'}</b></div>`;if(side!=='WAIT'){let x=levels(side,m15);renderLevels(x);if(bot&&!account.position)openPaperTrade(side,x)}}catch(e){console.error(e)}}
function openPaperTrade(side,x){let riskDollars=account.balance*.01;let units=riskDollars/x.risk;account.position={pair,side,entry:x.p,sl:x.sl,tp:x.tp,units};account.trades++;$('position').textContent=`OPEN ${side} · ${pair} · demo risk $${riskDollars.toFixed(2)}`;updateAccount(x.p)}
function updatePosition(price){if(!account.position){updateAccount(price);return}let p=account.position,delta=(price-p.entry)*(p.side==='BUY'?1:-1),pipValue=Math.abs(delta*p.units);$('pnl').textContent=(delta*p.units>=0?'+':'')+ (delta*p.units).toFixed(2)+' USD';if((p.side==='BUY'&&price<=p.sl)||(p.side==='SELL'&&price>=p.sl)){closeTrade(-1,price);return}if((p.side==='BUY'&&price>=p.tp)||(p.side==='SELL'&&price<=p.tp)){closeTrade(2,price);return}updateAccount(price)}
function closeTrade(result,price){let p=account.position;if(!p)return;let pnl=(price-p.entry)*(p.side==='BUY'?1:-1)*p.units;account.balance+=pnl;account.position=null;$('position').textContent=`CLOSED ${pnl>=0?'+':''}$${pnl.toFixed(2)} · demo trade`;updateAccount(price)}
function updateAccount(price){let unreal=account.position?(price-account.position.entry)*(account.position.side==='BUY'?1:-1)*account.position.units:0;$('balance').textContent='$'+account.balance.toFixed(2);$('equity').textContent='$'+(account.balance+unreal).toFixed(2);$('pnl').textContent=(unreal>=0?'+':'')+'$'+unreal.toFixed(2);$('tradeCount').textContent=account.trades}
$('bot').onclick=()=>{bot=!bot;$('bot').textContent=bot?'STOP BOT':'START BOT';if(bot){Promise.all(['15min','1h','4h'].map(i=>api(i))).then(([a,b,c])=>{cache['15min']=a.values;cache['1h']=b.values;cache['4h']=c.values;analyze()}).catch(console.error)}};
$('pair').onchange=()=>{pair=$('pair').value;$('pairLabel').textContent=pair;cache={};if(account.position){account.position=null;$('position').textContent='Pair changed · previous demo position closed';}load()};
document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{document.querySelector('.on').classList.remove('on');b.classList.add('on');tf=b.dataset.i;$('tfLabel').textContent=b.textContent;load()});
$('backtest').onclick=async()=>{let start=$('start').value,end=$('end').value;if(!start||!end)return;$('results').textContent='Running…';let [a,b,c]=await Promise.all(['15min','1h','4h'].map(i=>api(i,start,end)));let equity=10000,w=0,l=0,trades=0,peak=equity,dd=0;for(let i=220;i<a.values.length-50;i++){let one=b.values.filter(x=>x.time<=a.values[i].time),four=c.values.filter(x=>x.time<=a.values[i].time);if(one.length<220||four.length<220)continue;let T=decision(four,'trend'),S=decision(one,'setup'),M=decision(a.values.slice(0,i+1),'entry');if(!(T.side&&T.side===S.side&&S.ready&&M.side===T.side&&M.ready))continue;let x=levels(T.side,a.values.slice(0,i+1)),out=null;for(let j=i+1;j<Math.min(i+49,a.values.length);j++){let q=a.values[j];if(T.side==='BUY'&&q.low<=x.sl){out=-1;break}if(T.side==='BUY'&&q.high>=x.tp){out=2;break}if(T.side==='SELL'&&q.high>=x.sl){out=-1;break}if(T.side==='SELL'&&q.low<=x.tp){out=2;break}}if(out!==null){trades++;out>0?w++:l++;equity*=1+out*.01;peak=Math.max(peak,equity);dd=Math.max(dd,(peak-equity)/peak)}}let wr=trades?w/trades*100:0,pf=l?w*2/l:0;$('results').innerHTML=[['Trades',trades],['Win rate',wr.toFixed(1)+'%'],['Profit factor',pf.toFixed(2)],['Equity','$'+equity.toFixed(2)],['Max DD',(dd*100).toFixed(1)+'%']].map(x=>`<span class="metric">${x[0]}<b>${x[1]}</b></span>`).join('')};
init();updateAccount(0);load();live();liveTimer=setInterval(live,10000);historicalTimer=setInterval(load,300000);