const $=id=>document.getElementById(id);
let pair='EUR/USD',bot=false,chart,series,cache={};
const PERIOD={"1min":60,"5min":300,"15min":900};
let account=JSON.parse(localStorage.getItem('fxDemoAccount')||'null')||{balance:10000,position:null,trades:[]};
$('end').value=new Date().toISOString().slice(0,10);
const fmt=v=>Number(v).toFixed(pair.includes('JPY')?3:5);
const money=v=>(v<0?'-':'')+'$'+Math.abs(v).toFixed(2);
const save=()=>localStorage.setItem('fxDemoAccount',JSON.stringify(account));
function EMA(a,n){if(a.length<n)return null;let k=2/(n+1),v=a[0];for(let i=1;i<a.length;i++)v=a[i]*k+v*(1-k);return v}
function RSI(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){let d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}if(!l)return 100;return 100-100/(1+(g/n)/(l/n))}
function ATR(d,n=14){if(d.length<n+1)return 0;let s=0;for(let i=d.length-n;i<d.length;i++)s+=Math.max(d[i].high-d[i].low,Math.abs(d[i].high-d[i-1].close),Math.abs(d[i].low-d[i-1].close));return s/n}
function candleBull(c){return c.close>c.open && (c.close-c.open)>=Math.abs(c.high-c.low)*.45}
function candleBear(c){return c.close<c.open && (c.open-c.close)>=Math.abs(c.high-c.low)*.45}
function api(interval,start,end,outputsize){let q=new URLSearchParams({interval,symbol:pair,outputsize:outputsize||'5000'});if(start)q.set('start',start);if(end)q.set('end',end);return fetch('/.netlify/functions/market?'+q,{cache:'no-store'}).then(async r=>{let t=await r.text();if(!r.ok)throw Error(t);let j=JSON.parse(t);if(!j.ok)throw Error(j.error||'Market data unavailable');return j})}
function quote(){return fetch('/.netlify/functions/quote12?symbol='+encodeURIComponent(pair),{cache:'no-store'}).then(async r=>{let t=await r.text();if(!r.ok)throw Error(t);let j=JSON.parse(t);if(!j.ok)throw Error(j.error||'Quote unavailable');return j})}
function init(){try{chart=LightweightCharts.createChart($('chart'),{width:$('chart').clientWidth||800,height:460,layout:{background:{color:'#091624'},textColor:'#aab8c6'},grid:{vertLines:{color:'#10253a'},horzLines:{color:'#10253a'}},timeScale:{timeVisible:true,secondsVisible:false}});series=chart.addCandlestickSeries();addEventListener('resize',()=>chart.applyOptions({width:$('chart').clientWidth||800}));$('connection').textContent='● CHART READY'}catch(e){$('connection').textContent='● CHART ERROR';$('reason').textContent=e.message}}
function renderAccount(unreal=0){$('balance').textContent=money(account.balance);$('equity').textContent=money(account.balance+unreal);$('pnl').textContent=(unreal>=0?'+':'')+money(unreal);$('tradeCount').textContent=account.trades.length;if(account.position){let p=account.position;$('position').textContent=`OPEN ${p.side} · ${p.pair} · Entry ${fmt(p.entry)} · SL ${fmt(p.sl)} · TP ${fmt(p.tp)}`}else if(!$('position').textContent.startsWith('CLOSED'))$('position').textContent='No open demo trade'}
function updatePosition(price){let p=account.position;if(!p)return renderAccount();let unreal=(price-p.entry)*(p.side==='BUY'?1:-1)*p.units;if((p.side==='BUY'&&price<=p.sl)||(p.side==='SELL'&&price>=p.sl)||(p.side==='BUY'&&price>=p.tp)||(p.side==='SELL'&&price<=p.tp)){let exit=p.side==='BUY'?(price<=p.sl?p.sl:p.tp):(price>=p.sl?p.sl:p.tp),pnl=(exit-p.entry)*(p.side==='BUY'?1:-1)*p.units;account.balance+=pnl;account.position=null;account.trades.push({pair:p.pair,side:p.side,entry:p.entry,exit,pnl,time:Date.now()});save();$('position').textContent=`CLOSED ${pnl>=0?'+':''}${money(pnl)} demo trade`}renderAccount(unreal)}
function scoreSignal(d1,d5,d15){
  if(d1.length<80||d5.length<60||d15.length<60)return {side:'WAIT',score:0,reasons:['Not enough candles']};
  const c=d1.at(-1),prev=d1.at(-2),cl1=d1.map(x=>x.close),cl5=d5.map(x=>x.close),cl15=d15.map(x=>x.close);
  const e9=EMA(cl1,9),e21=EMA(cl1,21),e20_5=EMA(cl5,20),e50_5=EMA(cl5,50),e20_15=EMA(cl15,20),e50_15=EMA(cl15,50),r=RSI(cl1),atr=ATR(d1),
    range=Math.max(...cl1.slice(-30))-Math.min(...cl1.slice(-30)),support=Math.min(...d1.slice(-30).map(x=>x.low)),resistance=Math.max(...d1.slice(-30).map(x=>x.high));
  let buy=0,sell=0,br=[],sr=[];
  if(e20_15>e50_15){buy+=2;br.push('15m trend bullish')}else if(e20_15<e50_15){sell+=2;sr.push('15m trend bearish')}
  if(e20_5>e50_5){buy+=2;br.push('5m trend bullish')}else if(e20_5<e50_5){sell+=2;sr.push('5m trend bearish')}
  if(e9>e21&&c.close>e21){buy+=2;br.push('1m trend bullish')}else if(e9<e21&&c.close<e21){sell+=2;sr.push('1m trend bearish')}
  const nearSupport=(c.low<=support+atr*.35)||(prev.low<=support+atr*.35),nearResistance=(c.high>=resistance-atr*.35)||(prev.high>=resistance-atr*.35);
  if(nearSupport&&c.close>prev.close){buy+=2;br.push('support reaction')}if(nearResistance&&c.close<prev.close){sell+=2;sr.push('resistance reaction')}
  if(r>=52&&r<=68&&c.close>prev.close){buy+=1;br.push('momentum confirms')}if(r<=48&&r>=32&&c.close<prev.close){sell+=1;sr.push('momentum confirms')}
  if(candleBull(c)&&c.close>e9){buy+=2;br.push('bullish confirmation candle')}if(candleBear(c)&&c.close<e9){sell+=2;sr.push('bearish confirmation candle')}
  const healthy=atr>0&&range>=atr*2&&range<=atr*8;if(healthy){buy+=1;sell+=1}
  if(r>72){buy=Math.max(0,buy-2);br.push('RSI overheated')}if(r<28){sell=Math.max(0,sell-2);sr.push('RSI oversold')}
  let side=buy>=8&&buy>sell+1?'CALL':sell>=8&&sell>buy+1?'PUT':'WAIT';
  return {side,score:Math.max(buy,sell),buy,sell,atr,price:c.close,signalCandle:c.time,reasons:side==='CALL'?br:side==='PUT'?sr:[...br,...sr],regime:healthy?'ACTIVE':'NO-TRADE'};
}
function analyze(){if(!cache['1min']||!cache['5min']||!cache['15min'])return;const d1=closed(cache['1min']),d5=closed(cache['5min']),d15=closed(cache['15min']);let s=scoreSignal(d1,d5,d15);$('decision').textContent=s.side;$('decision').className=s.side.toLowerCase();$('reason').textContent=`${s.regime} · score ${s.score}/12 · ${s.reasons.slice(-3).join(' · ')||'No clean setup'}`;$('checks').innerHTML=`<div class="check">15m trend <b>${s.buy>s.sell?'BULLISH':s.sell>s.buy?'BEARISH':'NEUTRAL'}</b></div><div class="check">5m confirmation <b>${s.buy>=4?'YES':'NO'}</b></div><div class="check">1m momentum <b>${s.buy>5||s.sell>5?'YES':'NO'}</b></div><div class="check">Candle confirmation <b>${s.reasons.some(x=>x.includes('confirmation candle'))?'YES':'NO'}</b></div><div class="check">Market quality <b>${s.regime}</b></div><div class="check">Setup score <b>${s.score}/12</b></div>`;if(!s.price||s.side==='WAIT'){['entry','sl','tp','signalTime'].forEach(id=>$(id).textContent='—');return}const risk=Math.max(s.atr*.8,s.price*(pair.includes('JPY')?.0008:.00008)),sl=s.side==='CALL'?s.price-risk:s.price+risk,tp=s.side==='CALL'?s.price+risk*2:s.price-risk;$('entry').textContent=fmt(s.price);$('sl').textContent=fmt(sl);$('tp').textContent=fmt(tp);$('signalTime').textContent=new Date(s.signalCandle*1000).toISOString().slice(11,19)+' UTC';if(bot&&!account.position){let units=(account.balance*.01)/risk;account.position={pair,side:s.side==='CALL'?'BUY':'SELL',entry:s.price,sl,tp,units};save();renderAccount()}}
function closed(d){if(!d?.length)return[];const now=Math.floor(Date.now()/1000);return d.filter(x=>x.time+60<=now)}
function applyQuote(q){if(!q?.ok||!Number.isFinite(+q.price))return;const price=+q.price;let d=cache['1min']||[];const t=Math.floor((+q.timestamp||Date.now()/1000)/60)*60;if(d.length){let last=d.at(-1);if(t>last.time){last={time:t,open:price,high:price,low:price,close:price};d=[...d,last]}else{last={...last,high:Math.max(last.high,price),low:Math.min(last.low,price),close:price};d=[...d.slice(0,-1),last]}cache['1min']=d;series.update(last)}$('price').textContent=fmt(price);$('source').textContent='Twelve Data · live quote';$('connection').textContent='● LIVE';$('connection').style.color='#35d995';updatePosition(price);if(bot)analyze()}
async function load(){try{$('connection').textContent='● LOADING';const d=await api('1min',null,null,'5000');if(!d.values?.length)throw Error('No 1-minute candles returned');cache['1min']=d.values;series.setData(d.values);$('price').textContent=fmt(d.values.at(-1).close);$('source').textContent='Twelve Data · 1m candles';$('connection').textContent='● LIVE';if(bot)await loadAll()}catch(e){$('connection').textContent='● DATA ERROR';$('reason').textContent='Market data error: '+e.message}}
async function loadAll(){let [a,b,c]=await Promise.all([api('1min',null,null,'5000'),api('5min',null,null,'2000'),api('15min',null,null,'1000')]);cache['1min']=a.values;cache['5min']=b.values;cache['15min']=c.values;series.setData(a.values);$('price').textContent=fmt(a.values.at(-1).close);analyze()}
function countdown(){const sec=60-new Date().getUTCSeconds();$('countdown').textContent=`00:${String(sec%60).padStart(2,'0')}`;if(sec===60||sec===1)loadAll().catch(()=>{})}
$('pair').onchange=()=>{pair=$('pair').value;$('pairLabel').textContent=pair;cache={};account.position=null;save();load()};
$('bot').onclick=()=>{bot=!bot;$('bot').textContent=bot?'STOP BOT':'START BOT';if(bot)loadAll().catch(e=>$('reason').textContent=e.message)};
$('backtest').onclick=async()=>{try{$('results').textContent='Testing 1-minute strategy…';const [a,b,c]=await Promise.all([api('1min',$('start').value,$('end').value,'5000'),api('5min',$('start').value,$('end').value,'2000'),api('15min',$('start').value,$('end').value,'1000')]);let wins=0,losses=0,signals=0;const d=a.values;for(let i=120;i<d.length-2;i++){const one=d.slice(0,i),five=b.values.filter(x=>x.time<=d[i].time),fifteen=c.values.filter(x=>x.time<=d[i].time);let s=scoreSignal(one,five,fifteen);if(s.side==='WAIT')continue;signals++;let outcome=null;for(let j=i+1;j<Math.min(i+3,d.length);j++){let q=d[j];if(s.side==='CALL'&&(q.low<=s.price-s.atr*.8||q.high>=s.price+s.atr*1.6)){outcome=q.low<=s.price-s.atr*.8?'L':'W';break}if(s.side==='PUT'&&(q.high>=s.price+s.atr*.8||q.low<=s.price-s.atr*1.6)){outcome=q.high>=s.price+s.atr*.8?'L':'W';break}}if(outcome==='W')wins++;if(outcome==='L')losses++}const wr=signals?(wins/signals*100):0;$('results').innerHTML=[['Signals',signals],['Wins',wins],['Losses',losses],['Win rate',wr.toFixed(1)+'%']].map(x=>`<span class="metric">${x[0]}<b>${x[1]}</b></span>`).join('')}catch(e){$('results').textContent='Backtest error: '+e.message}};
init();renderAccount();load();quote().then(applyQuote).catch(e=>console.warn('Quote:',e));setInterval(()=>quote().then(applyQuote).catch(()=>{}),5000);setInterval(countdown,1000);setInterval(load,300000);countdown();